server:
  port: 8079

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    show-sql: false
